### ISSUE TITLE
Vagrant not syncing files/folders

### ISSUE THREAD

**Issue by FrancisNge** [chrisjackson-pellicle/paragone-nf#10]
Hi there,

I have an error with vagrant up and I think this might be why I can't get the folders from my local host PC to sync with the guest directory.

I'm using windows 10, have installed Oracle Virtual Box v6+.

interestingly, for some reason, I can start the virtual machine via the virtualBox user interface, but not when I try 'vagrant up' in the terminal.
I bypassed this issue by starting the VM via virtualBox, then entering 'vagrant ssh' via terminal to connect there which works. But then I don't see the folders with the config script etc.

I also attach a log file from virtualBox if that helps. I see there's no mount folder or sync folder in it...

I tried some debugging solutions online but thus far they have not worked. I wonder if it is to do with the vagrant configuration file (attached).

The error with vagrant up, or vagrant reload is as follows, in the terminal:
PS C:\Users\2022fn001\Downloads\vagrant-test> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'sylabs/singularity-3.6-ubuntu-bionic64' version '20201013.0.0' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "22048819-5b09-4198-bf00-6a2e030d85c2", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'paragone-test-sync-2023-2405' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

[VBox.log.1.txt](https://github.com/chrisjackson-pellicle/paragone-nf/files/11555560/VBox.log.1.txt)
[Vagrantfile.txt](https://github.com/chrisjackson-pellicle/paragone-nf/files/11555565/Vagrantfile.txt)

Cheers!
Francis

**Comment by chrisjackson-pellicle** [comment]
Hi @FrancisNge ,

I'm closing this issue as stale, but please re-open it if it's still a problem.
