### ISSUE TITLE
Paragone stop half way

### ISSUE THREAD

**Issue by FrancisNge** [chrisjackson-pellicle/paragone-nf#11]
Hi there, I have this issue half way when I run paragone. Do I need to check the Nextflow.log file? But I'm not sure where that would be located, it is not in the results output file.

vagrant@vagrant:~$ nextflow run ~/bin/paragone-nf/paragone.nf -c ~/bin/paragone-nf/paragone.config  --hybpiper_paralogs_directory ~/Hib/ --external_outgroups_file ~/ozbaits_external_outgroup.fasta --outdir ~/externalout/
N E X T F L O W  ~  version 23.04.1
Launching `/home/vagrant/bin/paragone-nf/paragone.nf` [thirsty_pesquet] DSL2 - revision: 908eeb28b6
executor >  local (14)
[08/df0d9e] process > CHECK_AND_BATCH_PARALOGS_01 (1) [100%] 1 of 1 ✔
[15/3213a9] process > ALIGN_AND_HMMCLEAN_02 (1)       [100%] 1 of 1 ✔
[da/9ec475] process > ALIGNMENT_TO_TREE_03 (1)        [100%] 1 of 1 ✔
[73/f53b81] process > TRIM_TIPS_04                    [100%] 1 of 1 ✔
[20/19f771] process > MASK_TIPS_05                    [100%] 1 of 1 ✔
executor >  local (14)
[08/df0d9e] process > CHECK_AND_BATCH_PARALOGS_01 (1) [100%] 1 of 1 ✔
[15/3213a9] process > ALIGN_AND_HMMCLEAN_02 (1)       [100%] 1 of 1 ✔
[da/9ec475] process > ALIGNMENT_TO_TREE_03 (1)        [100%] 1 of 1 ✔
[73/f53b81] process > TRIM_TIPS_04                    [100%] 1 of 1 ✔
[20/19f771] process > MASK_TIPS_05                    [100%] 1 of 1 ✔
[dc/01d88d] process > CUT_LONG_INTERNAL_BRANCHES_06   [100%] 1 of 1 ✔
[fd/162388] process > WRITE_ALIGNMENT_SUBSET_07       [100%] 1 of 1 ✔
[3e/a8dbd1] process > REALIGN_AND_IQTREE_08 (1)       [100%] 1 of 1 ✔
[a3/d52bc3] process > RESOLVE_POLYTOMIES              [100%] 1 of 1 ✔
[8b/75c76d] process > PRUNE_PARALOGS_MO_09            [100%] 1 of 1 ✔
[a9/22e307] process > PRUNE_PARALOGS_RT_10            [100%] 1 of 1 ✔
[86/c101e5] process > PRUNE_PARALOGS_MI_11            [  0%] 0 of 1
[6a/df5ba5] process > WRITE_ALIGNMENT_SUBSET_MO_12    [100%] 1 of 1, failed: 1 ✘
[95/fd0309] process > WRITE_ALIGNMENT_SUBSET_RT_13    [100%] 1 of 1, failed: 1 ✘
[-        ] process > WRITE_ALIGNMENT_SUBSET_MI_14    -
[-        ] process > STRIP_NAMES_AND_REALIGN_MO_15   -
[-        ] process > STRIP_NAMES_AND_REALIGN_RT_16   -
[-        ] process > STRIP_NAMES_AND_REALIGN_MI_17   -
ERROR ~ Error executing process > 'WRITE_ALIGNMENT_SUBSET_MO_12'

Caused by:
  Missing output file(s) `15_selected_alignments_MO_batch_folders/batch_*` expected by process `WRITE_ALIGNMENT_SUBSET_MO_12`

Command executed:

  mkdir all_realignments_combined
    for alignment in batch_1_outgroups_added_alignments
      do
        echo ${alignment}
        cp -r ${alignment}/* all_realignments_combined
      done

  mkdir 15_selected_alignments_MO

  python /Yang-and-Smith-RBGV-scripts/07a_subset_fasta_from_tree_and_batch.py   12_prune_MO_trees   .tre   all_realignments_combined   15_selected_alignments_MO   -batch_size 20

  mv 08_selected_alignments_batch_folders 15_selected_alignments_MO_batch_folders

Command exit status:
  0

Command output:
  batch_1_outgroups_added_alignments
  Namespace(tree_file_folder='12_prune_MO_trees', tree_file_extension='.tre', alignment_file_folder='all_realignments_combined', output_alignment_folder='15_selected_alignments_MO', from_cut_internal_branches=False, batch_size=20)
  Batches are: []

Work dir:
  /home/vagrant/work/6a/df5ba5d6acdf975cc8f47762472e20

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by chrisjackson-pellicle** [comment]
Hi @FrancisNge,

Are you able to share your data so I can investigate this? Feel free to PM them to me.

Alternatively, in the next couple of weeks I'll be releasing a new version of the `paragone-nf` pipeline. This new version will wrap the Python package [`ParaGone`](https://github.com/chrisjackson-pellicle/ParaGone), which includes new bug fixes, logging and reporting, and which should make troubleshooting a lot easier. If you can hold off until then, you could try the new version of the `paragone-nf` pipeline, and hopefully this error should go away...

Cheers,

Chris

**Comment by FrancisNge** [comment]
Hi @chrisjackson-pellicle , no problem I can wait and try out the new version of paragone. 

Cheers!
Francis

**Comment by chrisjackson-pellicle** [comment]
Hi @FrancisNge  - did you have better luck with the latest version?

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Closing as inactive - feel free to re-open!
