### ISSUE TITLE
Alternative virtual machines compatibility with Mac M1?

### ISSUE THREAD

**Issue by FrancisNge** [chrisjackson-pellicle/paragone-nf#9]
Hi Chris,

You mentioned that this pipeline is not compatible with the M1 chip Macs at the moment. Is that only because VirtualBox does not run on the M1 chip macs, or are there other incompatibility issues with the other related software and packages?

Apparently this runs on M1 chip macs:
https://mac.getutm.app

Cheers
Francis

**Comment by chrisjackson-pellicle** [comment]
Hi Francis,

Yes, at the time VirtualBox (and possibly Vagrant, although I can't recall now) didn't run on M1 chips. A quick google suggests that this has been resolved now; when I get a chance I'll test it and update the readme.

Cheers,

Chris

**Comment by chrisjackson-pellicle** [comment]
Hi Francis,

I've finally found time to check this. Although `VirtualBox` has some [test builds](https://www.virtualbox.org/wiki/Testbuilds) that successfully install on my M3 Mac, I can't get `vagrant` to successfully launch any boxes. I get the error:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'aborted' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.

``` 

A bit of googling found [this](https://github.com/hashicorp/vagrant/issues/13098) thread and [this](https://forums.virtualbox.org/viewtopic.php?f=8&t=107344) thread. So, it appears `vagrant`/`Virtualbox` combination till isn't a viable option on Apple Silicon (i.e. M1/M2/M3 chips) at this stage. I'll close the issue for now, and revisit it again in a year or so to see if things have changed...


Cheers,

Chris
